services:
  backend:
    build:
      context: ./serveur
      dockerfile: Dockerfile
    container_name: serveur
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    networks:
      - restaurant-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  frontend:
    build:
      context: ./client          # <-- contexte = dossier client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "${FRONTEND_PORT:-5173}:80"   # Nginx Ã©coute sur 80
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - restaurant-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  restaurant-net:
    driver: bridge