services:
  # ==========================
  # Backend NestJS
  # ==========================
  backend:
    build:
      context: ./serveur
      dockerfile: Dockerfile
    container_name: restaurant_backend
    environment:
      - DATABASE_URL=${DATABASE_URL} # URL de ta base Prisma en ligne
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    networks:
      - restaurant-net
    command: >
      sh -c "npx prisma migrate deploy &&
             node dist/main.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  # ==========================
  # Frontend React
  # ==========================
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: restaurant_frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"  # Align√© avec Nginx, ajustez si dev avec 5173
    depends_on:
      - backend
    networks:
      - restaurant-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  restaurant-net:
    driver: bridge
