services:
  # ==========================
  # Backend NestJS
  # ==========================
  backend:
    build: ./serveur
    container_name: restaurant_backend
    environment:
      DATABASE_URL: "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKWTE4QjlDUjcxM0NDMktLUFBEVlo5QloiLCJ0ZW5hbnRfaWQiOiIyODZmMzM4MDAwMDMyZTMwMDFiNzRkNjkyNWEyODY5YjI3NWI2MmE5M2JkMTBlN2VhYTg2YzU5MzVjZGQ4MjI3IiwiaW50ZXJuYWxfc2VjcmV0IjoiMDdhYWIyODYtNWVjMC00ZjYyLTljMDUtYWE5ZDU3MDViOGRlIn0.7zV56lrb2QidBb317kSSEwNe1-vzZh-WvmWnV5aPorw"  # URL de ta base Prisma en ligne
    ports:
      - "${BACKEND_PORT}:3000"
    networks:
      - restaurant-net
    command: >
      sh -c "npx prisma migrate deploy &&
             node dist/src/main.js"

  # ==========================
  # Frontend React
  # ==========================
  frontend:
    build: ./client
    container_name: restaurant_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - restaurant-net

networks:
  restaurant-net:
    driver: bridge
