version: '3.8'

services:
  # ==========================
  # Backend NestJS
  # ==========================
  backend:
    build: ./backend
    container_name: restaurant_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}   # URL de ta base Prisma en ligne
    ports:
      - "${BACKEND_PORT}:5000"
    networks:
      - restaurant-net
    command: >
      sh -c "npx prisma migrate deploy &&
             node dist/main.js"

  # ==========================
  # Frontend React
  # ==========================
  frontend:
    build: ./frontend
    container_name: restaurant_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - restaurant-net

networks:
  restaurant-net:
    driver: bridge
